### ISSUE TITLE
refreshing tiles

### ISSUE THREAD

**Issue by guy1ziv2** [mccarthyryanc/folium_gee#1]
Great tool - many thanks for putting this starting point !

I tried putting it into a Colaboratory document -
https://colab.research.google.com/drive/1NdgUrdkHzcoSSS_7iUdUgr8oLf9_xGab

When I zoom in on the map, I sometimes get areas that are 'missing' i.e. unloaded tiles. Occasionally, it appears these never get refreshed. Any thoughts why?

Guy

**Comment by mccarthyryanc** [comment]
@guy1ziv2 are you looking at a different AOI than the one specified in the colab doc? Perhaps an AOI that doesn't have imagery within the filtered date range? When I run it, everything looks good to me:
![github_folium_gee_issue](https://user-images.githubusercontent.com/997120/41553322-3fc2e426-72e6-11e8-90c7-4ca00e72a38c.gif)

**Comment by mccarthyryanc** [comment]
@guy1ziv2 actually, I did start to see some 'missing' tiles after adjusting the date range. However, it looked more like a lag in the GEE processing. If I waited a few seconds, or toggled the visibility in the 'visual' layer, the tiles eventually show up.
